name: Compile LaTeX Notes

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            Notas/main.tex
            work_in_root_file_dir: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
